#! python


def build(ctx):
    ctx(features="tex", source="main.tex", prompt=1, name="main")
    # Install to the project root.
    ctx.install_files(ctx.env.PROJECT_PATHS["PROJECT_ROOT"].abspath(), "main.pdf")
    # Running LaTeX processes in parallel leads to
    # too many potential problems.
    ctx.add_group()
